name 'jlust-sts'
version '0.1.0'
source 'https://github.com/jurgenlust/puppet-sts.git'
author 'jlust'
license 'unknow'
summary 'Puppet module for installing the SpringSource Tool Suite'
description 'Usage: include sts'
project_page 'https://github.com/jurgenlust/puppet-sts'
dependency ''